"""
Run Ingestion — Entry Point for Phase 2.

Reads generated JSON files from data/, cleans the data,
and stores valid rows into the raw_store_data table in PostgreSQL.

This script runs once (not on a schedule) — run it whenever
new JSON files have been generated by Phase 1.

Usage:
    python run_ingestion.py
"""

# datetime: used to print the current timestamp in status messages
from datetime import datetime

# Import our ingestion pipeline class
from pipeline.data_ingestion import DataIngestionPipeline


def main():
    """Run the data ingestion pipeline once."""

    # Print a startup banner
    print("=" * 60)
    print("  Nora's Supermarket — Data Ingestion Pipeline")
    print("=" * 60)

    # Print the current time for logging purposes
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"\n[{now}] Starting ingestion …")

    # Create the pipeline instance and run it
    # This will: scan data/ → clean each file → insert into DB → move to processed/
    pipeline = DataIngestionPipeline()
    pipeline.run()

    print("\nIngestion complete.")


# Standard Python pattern: only run main() when executed directly
if __name__ == "__main__":
    main()
