"""
Data Ingestion Pipeline.

Reads unprocessed JSON files from data/, cleans them via DataCleaner,
inserts the clean rows into the raw_store_data table, and moves the
processed files to data/processed/.
"""

# json: built-in module for reading JSON files
import json

# os: for file system operations (listing directories, checking paths)
import os

# shutil: provides high-level file operations (moving files between directories)
import shutil

# datetime: used to set the ingested_at timestamp on each record
from datetime import datetime

# Import our data cleaner class (Pandas-based data cleaning)
from cleaning.data_cleaner import DataCleaner

# Import directory paths from settings
from config.settings import DATA_DIR, PROCESSED_DIR

# Import database session factory and initialization function
from database.connection import SessionLocal, init_db

# Import the ORM model for the raw_store_data table
from models.raw_store_data import RawStoreData


class DataIngestionPipeline:
    """Orchestrates the pipeline: read JSON files → clean data → store in PostgreSQL."""

    def __init__(self):
        # Create an instance of the DataCleaner to clean each file's data
        self.cleaner = DataCleaner()

        # Create the processed/ directory if it doesn't exist yet
        # This is where we move files after they've been ingested
        os.makedirs(PROCESSED_DIR, exist_ok=True)

    def run(self):
        """Execute the full ingestion cycle once."""

        # Ensure database tables exist (creates them if they don't)
        init_db()

        # Get list of JSON files that haven't been processed yet
        json_files = self._get_unprocessed_files()

        # If there are no new files, exit early
        if not json_files:
            print("  No new files to process.")
            return

        # Create a new database session for this ingestion cycle
        session = SessionLocal()
        total_inserted = 0  # Counter for total records inserted

        try:
            # Process each JSON file one by one
            for filepath in json_files:
                count = self._process_file(filepath, session)
                total_inserted += count

            # Commit all inserts in a single transaction
            # This is more efficient and ensures atomicity (all-or-nothing)
            session.commit()
            print(f"  ✔ Committed {total_inserted} records to raw_store_data.")

        except Exception as e:
            # If anything goes wrong, rollback the transaction
            # This undoes all pending inserts so we don't have partial data
            session.rollback()
            print(f"  ✖ Ingestion failed: {e}")
            raise  # Re-raise so the caller knows it failed

        finally:
            # Always close the session, whether success or failure
            session.close()

    # ── private helpers ──────────────────────────────────────────────

    def _get_unprocessed_files(self) -> list[str]:
        """
        Return a list of .json file paths in DATA_DIR (excludes the processed/ subdirectory).
        These are files generated by Phase 1 that haven't been ingested yet.
        """
        # If the data directory doesn't exist yet, return empty list
        if not os.path.exists(DATA_DIR):
            return []

        # List all .json files in DATA_DIR (not in subdirectories like processed/)
        return [
            os.path.join(DATA_DIR, f)              # Build full path for each file
            for f in os.listdir(DATA_DIR)           # List all entries in data/
            if f.endswith(".json")                   # Only include .json files
            and os.path.isfile(os.path.join(DATA_DIR, f))  # Exclude subdirectories
        ]

    def _process_file(self, filepath: str, session) -> int:
        """
        Read, clean, insert, and move a single JSON file.

        Args:
            filepath: Full path to the JSON file
            session: SQLAlchemy database session

        Returns:
            Number of records inserted from this file.
        """
        # Extract just the filename for logging (e.g. "Branch_A_20260309_143000.json")
        filename = os.path.basename(filepath)
        print(f"  Processing: {filename}")

        # Read the JSON file and parse it into a list of dicts
        with open(filepath, "r", encoding="utf-8") as f:
            records = json.load(f)

        # Pass the raw records through our Pandas-based cleaner
        df = self.cleaner.clean(records)

        # If all records were invalid and got cleaned out, skip this file
        if df.empty:
            print(f"    ⚠ No valid records after cleaning in {filename}")
            self._move_to_processed(filepath)  # Still move it so we don't reprocess
            return 0

        # Convert each cleaned DataFrame row into a RawStoreData ORM object
        rows = []
        for _, row in df.iterrows():
            rows.append(
                RawStoreData(
                    branch=row["branch"],
                    item=row["item"],
                    quantity=int(row["quantity"]),       # Ensure Python int (not numpy int)
                    unit_price=float(row["unit_price"]), # Ensure Python float
                    total_price=float(row["total_price"]),
                    sold_at=row["sold_at"],              # Already a datetime from cleaner
                    payment_method=row["payment_method"],
                    cashier_name=row["cashier_name"],
                    ingested_at=datetime.utcnow(),       # Current UTC time
                )
            )

        # Add all ORM objects to the session (staged for insertion)
        # They won't be committed to the DB until session.commit() is called
        session.add_all(rows)
        print(f"    ✔ {len(rows)} records staged for insertion")

        # Move the file to processed/ so it won't be ingested again
        self._move_to_processed(filepath)
        return len(rows)

    def _move_to_processed(self, filepath: str):
        """
        Move a processed JSON file into the processed/ subdirectory.
        This prevents re-processing the same file on the next run.
        """
        # Build the destination path: data/processed/{filename}
        dest = os.path.join(PROCESSED_DIR, os.path.basename(filepath))

        # shutil.move works like "mv" — moves the file to the new location
        shutil.move(filepath, dest)
